package tela;
import dao.DAOCargo;
import DAO.DAOMinisterio;
import DAO.DAOMinisterioCargo;
import java.util.List;
import javax.swing.JOptionPane;
import pojo.Cargo;
import pojo.Ministerio;

public class cadastraCargo extends javax.swing.JFrame {
Cargo cargo = new Cargo();
DAOCargo daoCargo = new DAOCargo();
Ministerio ministerio = new Ministerio();
DAOMinisterio daoMinisterio = new DAOMinisterio();
DAOMinisterioCargo daoMinisterioCargo = new DAOMinisterioCargo();
List<Ministerio> listaMinisterio;
List<Cargo> listaCargo;

    public cadastraCargo() {
        initComponents();
        setSize(960,721);
        setResizable(false);
        
         listaMinisterio = daoMinisterio.buscar();
        for(Ministerio ministerio : listaMinisterio){
            nomeMinisterio.addItem(ministerio.getNome());
        }
        
        listaCargo = daoCargo.buscar();
        for (Cargo cargo : listaCargo){
            nomeCargo.addItem(cargo.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeCargo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        nomeMinisterio = new javax.swing.JComboBox<>();
        cadastrar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jFundo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Cargo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 50, 186, 30);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome do Cargo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 120, 140, 30);

        nomeCargo.setEditable(true);
        nomeCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        nomeCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCargoActionPerformed(evt);
            }
        });
        nomeCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeCargoKeyPressed(evt);
            }
        });
        getContentPane().add(nomeCargo);
        nomeCargo.setBounds(400, 120, 270, 30);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ministério:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 200, 90, 30);

        getContentPane().add(nomeMinisterio);
        nomeMinisterio.setBounds(400, 200, 270, 30);

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(330, 330, 90, 23);

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(530, 330, 90, 23);

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 540, 90, 23);

        jFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/wallpimg.jpg"))); // NOI18N
        jFundo2.setText("Cadastrar");
        getContentPane().add(jFundo2);
        jFundo2.setBounds(0, 0, 1012, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCargoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
         try{
        cargo.setNome(nomeCargo.getSelectedItem().toString());
        if(nomeCargo.getSelectedIndex()== -1){
            
        daoCargo.cadastrar(cargo);
        }else{
            //o combobox se inicia em 0
            for(Cargo cargo1 : listaCargo){
                if(cargo1.getNome() == nomeCargo.getSelectedItem().toString()){
                    cargo.setId(cargo1.getId());
                    break;
                }
            }
        }
        
        for(Ministerio ministerio1 : listaMinisterio){
                if(ministerio1.getNome() == nomeMinisterio.getSelectedItem().toString()){
                    ministerio.setId(ministerio1.getId());
                    break;
                }
            }
        
        daoMinisterioCargo.salvar(ministerio, cargo);
        limpar();
        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível realizar o cadastro!");
        }
                          
    }//GEN-LAST:event_cadastrarActionPerformed

    private void nomeCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCargoKeyPressed
        cargo.setNome(nomeCargo.getSelectedItem().toString());
    }//GEN-LAST:event_nomeCargoKeyPressed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirActionPerformed
private void limpar(){
    nomeCargo.setSelectedIndex(-1);
    nomeMinisterio.setSelectedIndex(-1);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/jFundo2/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastraCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastraCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastraCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastraCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastraCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jFundo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> nomeCargo;
    private javax.swing.JComboBox<String> nomeMinisterio;
    // End of variables declaration//GEN-END:variables
}
