/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import DAO.DAOMinisterio;
import dao.DAOMembro;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import pojo.Membro;
import pojo.Ministerio;

public class cadastraMembro extends javax.swing.JFrame {
   
    DAOMembro daoMembro = new DAOMembro();
    Membro membro = new Membro();
    DAOMinisterio daoMinisterio = new DAOMinisterio();
    Ministerio ministerio = new Ministerio();
    List<Ministerio> listaMinisterio;
    String ano, 
           mes, 
           dia;
    String dataNascimento;

    public cadastraMembro() {
        initComponents(); 
        setResizable(false);
        setSize(960, 720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        datanascv = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cidade = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        celular = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        cadastrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        excluir1 = new javax.swing.JButton();
        jLfundo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Membros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 50, 230, 30);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 430, 50, 30);
        getContentPane().add(id);
        id.setBounds(220, 120, 240, 30);

        limpar.setBackground(new java.awt.Color(255, 255, 255));
        limpar.setText("limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        getContentPane().add(limpar);
        limpar.setBounds(630, 120, 70, 30);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(220, 180, 430, 30);

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 120, 20, 30);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 180, 50, 30);

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "F", "M" }));
        getContentPane().add(sexo);
        sexo.setBounds(710, 180, 80, 30);

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 180, 40, 30);

        try {
            datanascv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(datanascv);
        datanascv.setBounds(220, 240, 270, 30);

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Nascimento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 240, 160, 30);

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpf);
        cpf.setBounds(570, 240, 220, 30);

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CPF");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 240, 40, 30);
        getContentPane().add(endereco);
        endereco.setBounds(220, 290, 270, 30);

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Endereço");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 290, 80, 30);

        cidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Alto Paraná", "Amaporã", "Cruzeiro do Sul", "Diamante do Norte", "Guairaçá", "Inajá", "Itaúna do Sul", "Jardim Olinda", "Loanda", "Marilena", "Mirador", "Nova Aliança do Ivaí", "Nova Londrina", "Paraíso do Norte", "Paranacity", "Paranapoema", "Paranavaí", "Planaltina do Paraná", "Porto Rico", "Querência do Norte", "Santa Cruz de Monte Castelo", "Santa Isabel do Ivaí", "Santa Mônica", "Santo Antônio do Caiuá", "São Carlos do Ivaí", "São João do Caiuá", "São Pedro do Paraná", "Tamboara", "Terra Rica" }));
        getContentPane().add(cidade);
        cidade.setBounds(570, 290, 220, 30);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 290, 60, 30);

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(telefone);
        telefone.setBounds(220, 340, 270, 30);

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefone");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 340, 68, 30);

        try {
            celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(celular);
        celular.setBounds(570, 340, 220, 30);

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Celular");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 340, 60, 30);
        getContentPane().add(usuario);
        usuario.setBounds(300, 430, 180, 30);

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel12.setText("Usuário");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 430, 60, 30);
        getContentPane().add(senha);
        senha.setBounds(560, 430, 190, 30);

        cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("cadastrar");
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(350, 590, 90, 23);

        cancelar.setBackground(new java.awt.Color(255, 255, 255));
        cancelar.setText("cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(553, 590, 90, 23);

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setText("buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(470, 120, 70, 30);

        excluir1.setBackground(new java.awt.Color(255, 255, 255));
        excluir1.setText("excluir");
        excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir1ActionPerformed(evt);
            }
        });
        getContentPane().add(excluir1);
        excluir1.setBounds(550, 120, 70, 30);

        jLfundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/grennabs.jpg"))); // NOI18N
        getContentPane().add(jLfundo1);
        jLfundo1.setBounds(0, 0, 960, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        Membro membro = new Membro();
        DAOMembro dao1 = new DAOMembro();
        
        membro.setNome(nome.getText());
        membro.setSexo(sexo.getSelectedItem().toString());
        dia = datanascv.getText().substring(0, 2);
        mes = datanascv.getText().substring(3, 5);
        ano = datanascv.getText().substring(6);
        membro.setDataNascimento(ano + "-" + mes + "-" + dia);

        membro.setCpf(cpf.getText());
        membro.setEndereco(endereco.getText());
        membro.setCidade(cidade.getSelectedItem().toString());
        membro.setTelefone(telefone.getText());
        membro.setCelular(celular.getText());
        membro.setUsuario(usuario.getText());
        membro.setSenha(senha.getText());
        dao1.salvar(membro);
        JOptionPane.showMessageDialog(null, "Cadastro concluído com sucesso!");
        dispose();
        
    }//GEN-LAST:event_cadastrarMouseClicked

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        limpar();
    }//GEN-LAST:event_limparActionPerformed

    private void excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir1ActionPerformed
        daoMembro.excluir(Integer.parseInt(id.getText().trim()));
        limpar();
        JOptionPane.showMessageDialog(null, "Membro excluído com sucesso!");
    }//GEN-LAST:event_excluir1ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        membro = daoMembro.buscaId(Integer.parseInt(id.getText()));
        nome.setText(membro.getNome());
        ano = membro.getDataNascimento().substring(0, 4);
        mes = membro.getDataNascimento().substring(5, 7);
        dia = membro.getDataNascimento().substring(8, 10);

        for (int i = 0; i < cidade.getItemCount() - 1; i++) {
            cidade.setSelectedIndex(i);
            if (membro.getCidade().equals(cidade.getItemAt(i))) {
                break;
            }
        }

        for (int j = 0; j < sexo.getItemCount() - 1; j++) {
            sexo.setSelectedIndex(j);
            if (membro.getSexo().equals(sexo.getItemAt(j))) {
                break;
            }
        }
        dataNascimento = dia + mes + ano;
        datanascv.setText(dataNascimento);
        cpf.setText(membro.getCpf());
        endereco.setText(membro.getEndereco());
        telefone.setText(membro.getTelefone());
        celular.setText(membro.getCelular());
        usuario.setText(membro.getUsuario());
        senha.setText(membro.getSenha());
    }//GEN-LAST:event_buscarActionPerformed
    private void limpar() {
        id.setText("");
        celular.setText("");
        cpf.setText("");
        datanascv.setText("");
        endereco.setText("");
        nome.setText("");
        senha.setText("");
        telefone.setText("");
        usuario.setText("");
        cidade.setSelectedIndex(-1);
        sexo.setSelectedIndex(-1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastraMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastraMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastraMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastraMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastraMembro().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JComboBox<String> cidade;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JFormattedTextField datanascv;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton excluir1;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLfundo1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
