
package tela;
import dao.DAOMembro;
import javax.swing.table.DefaultTableModel;
import pojo.Membro;

public class TabelaMembro extends javax.swing.JFrame {
        DefaultTableModel modelo;
        DAOMembro dao = new DAOMembro();
    public TabelaMembro() {
        initComponents();
        setResizable(false);
        setSize(800,700);
        modelo = (DefaultTableModel)tabela.getModel();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JScrollPane = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        botaoConsultar = new javax.swing.JButton();
        campoSair = new javax.swing.JButton();
        jFundo = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("usuário");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sexo", "CPF", "Data de Nascimento"
            }
        ));
        JScrollPane.setViewportView(tabela);

        getContentPane().add(JScrollPane);
        JScrollPane.setBounds(50, 150, 700, 404);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 63, 60, 40);
        getContentPane().add(campoNome);
        campoNome.setBounds(180, 70, 420, 30);

        botaoConsultar.setText("Consultar");
        botaoConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConsultarMouseClicked(evt);
            }
        });
        getContentPane().add(botaoConsultar);
        botaoConsultar.setBounds(610, 70, 90, 30);

        campoSair.setText("Sair");
        campoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoSairMouseClicked(evt);
            }
        });
        getContentPane().add(campoSair);
        campoSair.setBounds(650, 600, 51, 23);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/wallaas.jpg"))); // NOI18N
        jFundo.setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().add(jFundo);
        jFundo.setBounds(-40, -120, 1235, 972);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSairMouseClicked
        dispose();
    }//GEN-LAST:event_campoSairMouseClicked

    private void botaoConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoConsultarMouseClicked
        modelo.setNumRows(0);
        for(Membro m : dao.buscar(campoNome.getText())){
            modelo.addRow(new Object[]{m.getId(),m.getNome(),m.getSexo(),m.getCpf(),m.getDataNascimento()});   
        }
        campoNome.setText("");
    }//GEN-LAST:event_botaoConsultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaMembro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JButton campoSair;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
