/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telav2;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;

/**
 *
 * @author Karina
 */
public class PainelBotoes extends javax.swing.JPanel {
    
    //List<JTextField> lista = new ArrayList<JTextField>();
    List<MeuCampo> lista = new ArrayList<MeuCampo>();
    
    public PainelBotoes() {
        initComponents();
        
    }

    /*public void habilitarCampos(boolean status){
        //primeiro passo - pegar a referência do container 
        JInternalFrame container = (JInternalFrame) getFocusCycleRootAncestor();
        
        for (int i = 0; i < container.getContentPane().getComponentCount(); i++) {
            //varre todos os componentes
            Component c = container.getContentPane().getComponent(i);
            if(c instanceof MeuCampo){
                //apaga os valores
                MeuCampo field = (MeuCampo) c;
                field.setEnabled(status);
            }
        }
    }
    
    public void limparCampos(){
        JInternalFrame container = (JInternalFrame) getFocusCycleRootAncestor();
        
        for (int i = 0; i < container.getContentPane().getComponentCount(); i++) {
            //varre todos os componentes
            Component c = container.getContentPane().getComponent(i);
            if(c instanceof MeuCampo){
                //apaga os valores
                MeuCampo field = (MeuCampo) c;
                field.setText("");
            }
        }
    }*/
    
    public List<MeuCampo> gerarLista(){
        //if(lista.size()==0){
            JInternalFrame container = (JInternalFrame) getFocusCycleRootAncestor();
        
        for (int i = 0; i < container.getContentPane().getComponentCount(); i++) {
            //varre todos os componentes
            Component c = container.getContentPane().getComponent(i);
            if(c instanceof MeuCampo){
                //apaga os valores
                MeuCampo field = (MeuCampo) c;
                lista.add(field);
            }
        }
        //}
        return lista;
    }
    
    public void habilitarCampos(boolean status){
        for(MeuCampo m: gerarLista()){
            m.setEnabled(status);
        }
    }
    
    public void limparCampos(){
        for(MeuCampo m: gerarLista()){
            m.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoConsultar = new javax.swing.JButton();
        botaoInserir = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoConfirmar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        botaoConsultar.setText("Consultar");

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.setEnabled(false);

        botaoExcluir.setText("Excluir");
        botaoExcluir.setEnabled(false);

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.setEnabled(false);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(botaoInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
        // TODO add your handling code here:
        habilitarCampos(true);
    }//GEN-LAST:event_botaoInserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoInserir;
    // End of variables declaration//GEN-END:variables
}
