/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telav2;

import conexao.Conexao;
import java.util.Scanner;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import tela.cadastraMembro;

/**
 *
 * @author Pedro
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setSize(1280,720);
        setResizable(false);
        Conexao retorno = new Conexao();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        cadastrar = new javax.swing.JButton();
        login = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        ibutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("não está cadastrado?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 320, 170, 23);

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 100, 60, 23);

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(540, 100, 260, 30);
        getContentPane().add(senha);
        senha.setBounds(540, 150, 260, 30);

        cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("cadastrar");
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(610, 360, 90, 23);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setText("login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(620, 230, 70, 23);

        sair.setBackground(new java.awt.Color(255, 255, 255));
        sair.setText("sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(1030, 620, 49, 23);

        ibutton.setBackground(new java.awt.Color(255, 255, 255));
        ibutton.setText("sobre");
        ibutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ibuttonMouseClicked(evt);
            }
        });
        ibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(ibutton);
        ibutton.setBounds(1100, 620, 60, 23);

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 150, 50, 23);

        jLFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/wallaas.jpg"))); // NOI18N
        getContentPane().add(jLFundo);
        jLFundo.setBounds(0, 0, 1280, 709);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
          
    }//GEN-LAST:event_cadastrarActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        cadastraMembro chama = new cadastraMembro();
            chama.setVisible(true);
    }//GEN-LAST:event_cadastrarMouseClicked

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void ibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibuttonActionPerformed

    private void ibuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibuttonMouseClicked
        JOptionPane.showMessageDialog(null,"Aplicativo desenvolvido em 2016 por Karina Mayumi Johansson e Pedro Arthur Passos da Silva\nInstituto Federal do Paraná - campus Paranavaí");
    }//GEN-LAST:event_ibuttonMouseClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        dispose();
    }//GEN-LAST:event_sairMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        Scanner entrada = new Scanner (System.in);
        String retorna = usuario.getText();
        String retorna1 = senha.getText();
        
     //   JOptionPane.showMessageDialog(null,""+retorna+" "+retorna1);
        if(retorna.equals("administrador")&& retorna1.equals("123")){
        dispose();
        telaAdm telaAdm = new telaAdm();
        telaAdm.setVisible(true);
    }
        else{
            JOptionPane.showMessageDialog(null,"Usuário e/ou senha incorretos");
        }
        
        //INICIALIZAR SINCRONIZAÇÃO COM BD
    }//GEN-LAST:event_loginMouseClicked

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton ibutton;
    private javax.swing.JLabel jLFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JButton sair;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
